name: CI Pruebas Python, Cobertura y Terraform

# Se ejecuta en cada 'push' y en cada 'pull_request' (PR) a la rama 'main' o 'develop'
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  # Definimos un único trabajo llamado 'build-and-test'
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip' # Activar cache para 'pip'

      # Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Instalar TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Inicializar Terraform (para validate)
        run: terraform init

        working-directory: ./infra/terraform

      - name: Ejecutar Pruebas y Cobertura
        run: make test

      - name: Ejecutar Validación de IaC (Terraform)
        run: make lint-iac
      
      - name: Ejecutar TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./infra/terraform